# ========== Comando para crear y levantar docker
# clear; docker compose up --build -d
# ========== 

services:
  permont-db:
    build: .
    container_name: PermontDB
    ports:
      - "503:503"
    volumes:
      - ./Files/Data:/app/Files/Data
    command: ["./Files/Scripts/bash/start.sh"]
